name: Push Images

on:
  push:
    tags:
      - '*'

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: ['jkube-java-binary-s2i', 'jkube-jetty9-binary-s2i', 'jkube-karaf-binary-s2i', 'jkube-tomcat9-binary-s2i']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CEKit
        uses: manusa/actions-setup-cekit@v1.0.0
      - name: Get Tag
        id: get_version
        run: |
          export GITHUB_TAG=${GITHUB_REF/refs\/tags\//}
          echo ::set-env name=TAG::quay.io/jkube/${{ matrix.image }}:${GITHUB_TAG/v/}
      - name: Build ${{ matrix.image }}
        run: |
          echo "Building ${TAG}"
          cekit --descriptor ${{ matrix.image }}.yaml build docker --tag="${TAG}"
      - name: Push quay.io/jkube/${{ matrix.image }}
        run: |
          echo "Pushing ${TAG}"
          docker login -u=${{ secrets.QUAY_USER }} -p=${{ secrets.QUAY_TOKEN }} quay.io
          docker push ${TAG}

